### PR TITLE
Plugins

### PR DESCRIPTION
**Pull request by deontologician**
Made this PR for watching plugins grow as a spectator sport.

---

This change is [Reviewable](https://reviewable.io/reviews/rethinkdb/horizon/760)

### CODE REVIEW

**Comment by danielmewes** [comment]
I'll see if we can set this up on the office projector.

**Comment by dalanmiller** [comment]
Odds 2:1 that @mlucy will have more commits than @Tryneus by merge time.

**Comment by deontologician** [comment]
I am imagining the look @mlucy gave @Tryneus when he saw the bracket spacing eslint rule. Immediately afterward it was changed.

**Comment by Tryneus** [comment]
Closing in favor of #865

**Pull request closed without merging**
