### PR TITLE
Added operators on to Observable.

### PR DESCRIPTION
**Pull request by cschram**
Updated Observable operator dependencies to add on to the Observable prototype, per #532.

---

This change is [Reviewable](https://reviewable.io/reviews/rethinkdb/horizon/540)

### CODE REVIEW

**Comment by deontologician** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/rethinkdb/horizon/540#-KJ8BxSZEg9WB4aTmwl8:-KJ8BxSZEg9WB4aTmwl9:-99627998) (no related file):_
This is an awesome start, thanks for the PR @cschram . I added a few comments on what needs to change, and in addition, the test code needs to be converted as well (this is really annoying, there are a lot of test files, so let me know if you aren't feeling up for it)

---

_[client/src/ast.js, line 4 [r1]](https://reviewable.io:443/reviews/rethinkdb/horizon/540#-KJ8BRRFQTSe0eeE1kxw:-KJ8BRRFQTSe0eeE1kxx:625706030) ([raw file](https://github.com/rethinkdb/horizon/blob/f18e951e1f4ae8697755b378c3085069627196f3/client/src/ast.js#L4)):_

> ``` JavaScript
> require('rxjs/add/observable/empty')
> 
> require('rxjs/add/operator/publishReplay')
> ```

All of these requires should probably look like:

``` js
import 'rxjs/add/operator/scan'
```

---

_[client/src/ast.js, line 8 [r1]](https://reviewable.io:443/reviews/rethinkdb/horizon/540#-KJ8BfN41GgfZx-05IgB:-KJ8BfN41GgfZx-05IgC:338325208) ([raw file](https://github.com/rethinkdb/horizon/blob/f18e951e1f4ae8697755b378c3085069627196f3/client/src/ast.js#L8)):_

> ``` JavaScript
> require('rxjs/add/operator/filter')
> require('rxjs/add/operator/map')
> require('rxjs/add/operator/toArray')
> ```

Also, we should probably move all of the operator additions to a single module that gets imported all at once from `index.js`, rather than adding the monkeypatches at the top of every file.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/540)_

**Comment by deontologician** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/540)_

**Comment by deontologician** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[client/src/ast.js, line 8 [r1]](https://reviewable.io:443/reviews/rethinkdb/horizon/540#-KJ8BfN41GgfZx-05IgB:-KJ8DT0mzVZSiDhMQDgZ:-119870760) ([raw file](https://github.com/rethinkdb/horizon/blob/f18e951e1f4ae8697755b378c3085069627196f3/client/src/ast.js#L8)):_
<details><summary>

<i>Previously, deontologician (Josh Kuhn) wrote…</i></summary>



> Also, we should probably move all of the operator additions to a single module that gets imported all at once from `index.js`, rather than adding the monkeypatches at the top of every file.
> </details>
> Actually, scratch this. The conversion to typescript will want these imports in each file

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/540)_

**Comment by cschram** [comment]
> Actually, scratch this. The conversion to typescript will want these imports in each file

Whoops, missed that part and went ahead and separated them out. Will fix :)

**Comment by deontologician** [comment]
:lgtm:

<details><summary>

<i>Previously, cschram (Corey Schram) wrote…</i></summary>



> > Actually, scratch this. The conversion to typescript will want these imports in each file
> 
> Whoops, missed that part and went ahead and separated them out. Will fix :)
> </details>

---

Reviewed 5 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/540#-:-KJNFgBBSB7XG2hJPUdy:1417088721)_

**Comment by deontologician** [comment]
Thanks, I also cherry-picked this onto the v1.x.x branch

**Pull request merged**
