### PR TITLE
Using "mime-types" to detect mime-type

### PR DESCRIPTION
**Pull request by zubair-io**
For one of my project I needed richer mime-type detection, this is what I did for that. I hope it is useful

---

This change is [Reviewable](https://reviewable.io/reviews/rethinkdb/horizon/438)

### CODE REVIEW

**Comment by deontologician** [comment]
Thank you! This has been an ugly hack since we put it in :)

**Comment by deontologician** [comment]
Technically, the server also has the capability to serve static files (separate from the cli static server). I am wondering if we should fix both at the same time

**Comment by zubair-io** [comment]
Makes sense, I can add it there too

**Comment by deontologician** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[a discussion](https://reviewable.io:443/reviews/rethinkdb/horizon/438#-KI9bOMz8ABNcUWjHcnl:-KI9bOMz8ABNcUWjHcnm:-670508550) (no related file):_
Ok, so we can merge this after the server static files also use mime-types

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/438)_

**Comment by zubair-io** [comment]
I added mime-types for the server

**Comment by deontologician** [comment]
:lgtm:

<details><summary>

<i>Previously, helixten (Zubair Lawrence) wrote…</i></summary>



> I added mime-types for the server
> </details>

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/438#-:-KIA5edY8Jh4S8VKivx_:1417088721)_

**Pull request merged**
