### PR TITLE
Auto Dependency Updates ...

### PR DESCRIPTION
**Pull request by lguzzon**
This change is [Reviewable](https://reviewable.io/reviews/rethinkdb/horizon/861)

### CODE REVIEW

**Comment by lguzzon** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/861)*

**Comment by lguzzon** [comment]
Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/861)*

**Comment by lguzzon** [comment]
Waiting patiently ...

**Comment by sp90** [comment]
@lguzzon im afraid that the project is dead

**Comment by rnenjoy** [comment]
No its not dead. They had a meeting last week and are organizing everything.

**Comment by sp90** [comment]
@rnenjoy ahh nice, i really hope that we get everything moving 👍

**Comment by BartNetJS** [comment]
I really hope so too.
For anyone interested. I have forked here https://github.com/SpikesBE/horizon
With azure ad authentication added to the repo (will create a pull request, once the horizon team is up and running again).
I've added a side note to the readme

**Pull request closed without merging**
