### PR TITLE
use AnonymousSubject as a base for HorizonSocket

### PR DESCRIPTION
**Pull request by Frizi**
response to breaking change https://github.com/ReactiveX/rxjs/commit/ba9ef2bbeef60f63acdfaa3a8cb6b0f84e90d404

---

This change is [Reviewable](https://reviewable.io/reviews/rethinkdb/horizon/491)

### CODE REVIEW

**Comment by deontologician** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[a discussion](https://reviewable.io:443/reviews/rethinkdb/horizon/491#-KIUcwhk0o2Aw6Dg4jE3:-KIUcwhk0o2Aw6Dg4jE4:-1181262046) (no related file):_
@frizi Are we making use of the behavior that's being changed here? We ported from RxJS 4 to 5, it's likely this is fixing some issues we weren't aware of

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/491)_

**Comment by deontologician** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/491)_

**Comment by Frizi** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[a discussion](https://reviewable.io:443/reviews/rethinkdb/horizon/491#-KIUcwhk0o2Aw6Dg4jE3:-KIWgLt-7Lqjuop3hsmR:2033898037) (no related file):_
<details><summary>

<i>Previously, deontologician (Josh Kuhn) wrote…</i></summary>



> @frizi Are we making use of the behavior that's being changed here? We ported from RxJS 4 to 5, it's likely this is fixing some issues we weren't aware of
> </details>
> Hey. This change lives in rxjs beta 8, that's why you are not yet aware of it. I haven't realized you are depending specifically beta 7. The change is essential for HorizonSocket to work with newer release, otherwise the internal observable is never subscribed and websocket is not being opened.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/491)_

**Comment by deontologician** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[a discussion](https://reviewable.io:443/reviews/rethinkdb/horizon/491#-KIUcwhk0o2Aw6Dg4jE3:-KI_EdLLcGQPqU2M7hm6:580966189) (no related file):_
<details><summary>

<i>Previously, Frizi (Paweł Grabarz) wrote…</i></summary>



> Hey. This change lives in rxjs beta 8, that's why you are not yet aware of it. I haven't realized you are depending specifically beta 7. The change is essential for HorizonSocket to work with newer release, otherwise the internal observable is never subscribed and websocket is not being opened.
> </details>
> Ok, I think we should merge this for the next major release then, because we don't want to break backwards compatibility in a minor release

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/491)_

**Comment by deontologician** [comment]
I'm going to do this as part of #531 , so closing this one. Thanks @Frizi for the PR

**Pull request closed without merging**
