### PR TITLE
remove isomorphic-fetch and imports/exports loaders (fixes #590, #571, #477, #420)

### LINKED ISSUE #590: Distributed code should not contain webpack specific logic
There is a require statement in the client https://github.com/rethinkdb/horizon/blob/next/client/src/util/fetch.js#L6 which is webpack specific and therefore when I attempt to build using typescript I come up against the following error:

```
Error: Cannot find module 'imports?this=>global!exports?global.fetch!isomorphic-fetch' from '/Users/home/demo/node_modules/@horizon/client/lib/util'
```

### PR DESCRIPTION
**Pull request by flipace**
replace webpack specific syntax in fetch.js and move it to webpack config

---

This change is [Reviewable](https://reviewable.io/reviews/rethinkdb/horizon/593)

### CODE REVIEW

**Comment by deontologician** [comment]
The tests are failing for some reason. It looks like the module not found error, but you explicitly remove that require, so I'm not sure what's causing it

**Comment by flipace** [comment]
Did you reinstall the dependencies?
Am 15.06.2016 7:11 Nachm. schrieb "Josh Kuhn" notifications@github.com:

**Comment by flipace** [comment]
@deontologician sorry my fault. will fix.

**Comment by flipace** [comment]
Things to keep in mind now:

I changed it to just use the whatwg-fetch. It's just a polyfill for browsers.
All the "universal" fetch packages had flaws in combination with the build chain which i have not been able to work around.

What that means is just that, if you use the horizon client somewhere else than web - people have to make sure that fetch is either available natively or via a manually added polyfill.

I've been able to successfully use the client in node too. I had to put WebSocket onto the global object though before requiring/importing @horizon/client.

**Comment by deontologician** [comment]
:clap:

**Comment by deontologician** [comment]
:lgtm: merging

**Comment by flipace** [comment]
I sure hope this resolves most of the problems with fetch. I didnt have a chance to give it a spin with react native though, would be great if someone could try

**Comment by benjick** [comment]
@flipace I would be glad to test, how would I do that? Just pull this and build?

**Comment by flipace** [comment]
@benjick I'm not sure tbh. I know that React Native has some issues when you try to npm link packages, so you might have to pull the _next_ branch and copy it directly into your projects node_modules folder.

**Comment by passcod** [comment]
Any ETA on when a version with this will be released? It's a blocker for my projects…

**Comment by danielmewes** [comment]
@passcod This will go into Horizon 2.0.0. We were hoping to release a release candidate of 2.0.0 this week, but I think it's going to be early next week.

**Comment by dalanmiller** [comment]
FYI - Horizon 2.0 beta has been released:

https://discuss.horizon.io/t/horizon-v2-0-0-beta/433

2016-08-05 17:28 GMT-07:00 Daniel Mewes notifications@github.com:

**Comment by passcod** [comment]
Great, thank you!

**Pull request merged**
