### PR TITLE
Add rethinkdb_data to gitignore

### PR DESCRIPTION
**Pull request by deontologician**
Part of #411 

@dalanmiller could you check this out and decide if we need to do anything else to prevent data from getting into the npm package?

---

This change is [Reviewable](https://reviewable.io/reviews/rethinkdb/horizon/430)

### CODE REVIEW

**Comment by danielmewes** [comment]
Wonder if this is really the right approach, since there were other files (rethinkdb_data_test) included in the current NPM as well.

It is also possible to configure _positive_ rules by negating a line in .npmignore. We could limit to certain file endings. Would that make sense?
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by danielmewes** [comment]
Actually as far as I could find out, we'd need to have a set of file ending rules for each directory depth. It becomes a bit annoying. (Edit: or maybe not, `**/` might work for this)

Maybe another option is writing our own short `publish.sh` script, that does the following:
1. Call `git status | grep -q "working directory clean"` and check the return code. If it returns anything other than 0, we print an error and abort.
2. Call `npm publish`

**Comment by danielmewes** [comment]
Such a script might be better since it generally stops us from publishing uncommitted changes or any extra files.

**Comment by deontologician** [comment]
That would be pretty nice.

**Comment by danielmewes** [comment]
@dalanmiller How exactly and from where do you run `npm publish`? I'm happy to write the script.

**Comment by deontologician** [comment]
I opened #431 to track creating such a script. I still think this PR is useful since we shouldn't accidentally commit rethinkdb_data directories to git either

**Comment by deontologician** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/430)_

**Pull request merged**
