### PR TITLE
hz schema streamlining 

### PR DESCRIPTION
**Pull request by dalanmiller**
Satisfies #548 
- Adds schema file loading to `hz serve`  

```
parser.addArgument([ '--schema-file' ],
    { type: 'string', metavar: 'SCHEMA_FILE_PATH',
      help: 'Path to the schema file to use, ' +
      'will attempt to load schema before starting Horizon server".' });
```
- Moves `get-schema` and `set-schema` to `hz schema save` and `hz schema load` respectively. 
  - `get-schema.js` and `set-schema.js` have been merged into `schema.js`. 
  - I propose it either stays this way or I re-seperate the commands into individual files under a `/cli/src/schema` folder. 
  - This is to help later when we potentially add more schema manipulation commands.
- Also adds `secrets.toml` and `schema.toml` 

Some warts: 
- I'm not sure [if there's a better way to check which command is being called in this context](https://github.com/rethinkdb/horizon/blob/dalanmiller_hz_schema_streamline_548/cli/src/schema.js#L532). 
- RethinkDB vomit logs when running tests
  screenshot 2016-07-26 16 57 25
- [Needs more complicated test cases here](https://github.com/rethinkdb/horizon/blob/dalanmiller_hz_schema_streamline_548/cli/test/schema.spec.js#L17-L32)

---

This change is [Reviewable](https://reviewable.io/reviews/rethinkdb/horizon/679)

### CODE REVIEW

**Comment by deontologician** [comment]
Is this ready to be reviewed?

**Comment by deontologician** [comment]
Also :clap: this is awesome

**Comment by dalanmiller** [comment]
I thought so @deontologician but the merge with `next` brought some new fails ❌, let me fix first.

**Comment by dalanmiller** [comment]
Now ready for review ✅ , praise be to Our Lady of Perpetual Exemption for tests that remedy my stupidity. 😅

**Comment by deontologician** [comment]
Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 2 of 4 files at r3, 2 of 5 files at r5, 1 of 2 files at r6.
Review status: 9 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

_[cli/src/init.js, line 231 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi-GMjnDYmVTCSItXo:-KNi-GMjnDYmVTCSItXp:1590367651) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/src/init.js#L231)):_

> ``` JavaScript
>       '.hz/config.toml',
>       makeDefaultConfig(projectName),
>       permission
> ```

Since we don't have secrets in this any more, we should probably remove the 0600 permissions from config.toml and just have it on secrets.toml

---

_[cli/src/schema.js, line 1 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi-lqA3jEyV9PE1lec:-KNi-lqBkSQS7pCVglOV:472832009) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/src/schema.js#L1)):_

> ``` JavaScript
> 'use strict';
> ```

Since this file is two files combined mostly, could you point out which parts are new?

---

_[cli/src/serve.js, line 234 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi0L6XAYl2FDLJTMCA:-KNi0L6XAYl2FDLJTMCB:961713901) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/src/serve.js#L234)):_

> ``` JavaScript
> };
> 
> const file_server = (distDir) => (req, res) => {
> ```

why the change from `file_server` to `fileServer` ?

---

_[cli/src/serve.js, line 251 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi0Dgo_W56a32Zv6lR:-KNi0Dgo_W56a32Zv6lS:1948015724) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/src/serve.js#L251)):_

> ``` JavaScript
>   return new Promise((resolve) => {
>     opts.bind.forEach((host) => {
>       console.log(host)
> ```

Should this be here?

---

_[cli/src/serve.js, line 767 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi1Jy6EvJMtiKKMx8U:-KNi1Jy6EvJMtiKKMx8V:-2111961573) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/src/serve.js#L767)):_

> ``` JavaScript
> };
> 
> serve.addArguments = addArguments;
> ```

Style change?

---

_[cli/test/schema.spec.js, line 168 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi2Ezwwwnys_lm3Rtf:-KNi2Ezx-LqIkkBgA4Th:799249003) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/test/schema.spec.js#L168)):_

> ``` JavaScript
>       mockFs.restore();
>     });
>     it('can parse a valid schema.toml file', (done) => {
> ```

We should probably add more extensive tests eventually for the schema.toml format, since it's underspecified right now 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/679)_

**Comment by dalanmiller** [comment]
Review status: 7 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

_[cli/src/init.js, line 231 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi-GMjnDYmVTCSItXo:-KNi_BDXY3CM9JxZswNn:-885138906) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/src/init.js#L231)):_
<details><summary>

<i>Previously, deontologician (Josh Kuhn) wrote…</i></summary>



> Since we don't have secrets in this any more, we should probably remove the 0600 permissions from config.toml and just have it on secrets.toml
> </details>
> Done. Made schema and config.toml 666

---

_[cli/src/schema.js, line 468 [r7]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNiYzEnbkV9WILxg3Ee:-KNiYzEnbkV9WILxg3Ef:-1177192123) ([raw file](https://github.com/rethinkdb/horizon/blob/c9cbdc469fcb133d45f4e48fd5fc4875a4a0d0ac/cli/src/schema.js#L468)):_

> ``` JavaScript
>   }).then(() => {
>     conn.close();
>     if(shutdown){ 
> ```

I had to add this, as running `hz serve --schema-file .hz/schema.toml` would run this command which automatically shut down the process. This is fine when you just want to start up RethinkDB to load the schema with `hz schema load` but not when you want to continue doing other things.

---

_[cli/src/schema.js, line 530 [r7]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNiYr-F1QZI2-tzkKoW:-KNiYr-F1QZI2-tzkKoX:676923663) ([raw file](https://github.com/rethinkdb/horizon/blob/c9cbdc469fcb133d45f4e48fd5fc4875a4a0d0ac/cli/src/schema.js#L530)):_

> ``` JavaScript
> // Avoiding cylical depdendencies
> schema.addArguments = addArguments;
> schema.processConfig = (options) => {
> ```

New

---

_[cli/src/schema.js, line 538 [r7]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNiYsLH4QvAthc3x8xp:-KNiYsLH4QvAthc3x8xq:160383579) ([raw file](https://github.com/rethinkdb/horizon/blob/c9cbdc469fcb133d45f4e48fd5fc4875a4a0d0ac/cli/src/schema.js#L538)):_

> ``` JavaScript
>   }
> };
> schema.runCommand = (options, done) => {
> ```

New

---

_[cli/src/serve.js, line 234 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi0L6XAYl2FDLJTMCA:-KNiWmVDCPUqr9aDQJMo:-1657876110) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/src/serve.js#L234)):_
<details><summary>

<i>Previously, deontologician (Josh Kuhn) wrote…</i></summary>



> why the change from `file_server` to `fileServer` ?
> </details>
> So at first I went all in camelCase but then I retracted a bit because of requirements in other files. Mostly I tried to follow this => https://rethinkdb-team.slack.com/archives/horizon/p1467249697000507

---

_[cli/src/serve.js, line 251 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi0Dgo_W56a32Zv6lR:-KNiXp3HAr-9GFHQfJiX:-499146009) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/src/serve.js#L251)):_
<details><summary>

<i>Previously, deontologician (Josh Kuhn) wrote…</i></summary>



> Should this be here?
> </details>
> Done.

---

_[cli/src/serve.js, line 767 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi1Jy6EvJMtiKKMx8U:-KNiXrgkbv0QoKZIy80v:302277424) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/src/serve.js#L767)):_
<details><summary>

<i>Previously, deontologician (Josh Kuhn) wrote…</i></summary>



> Style change?
> </details>
> There was a circular dependency between `serve.js` and `schema.js` - https://nodejs.org/api/modules.html#modules_cycles.
> This pattern is one way to get around it, that I confirmed with Marshall. 

---

_[cli/test/schema.spec.js, line 168 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi2Ezwwwnys_lm3Rtf:-KNi_OOsHfTfsh7uQ0qS:1263711107) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/test/schema.spec.js#L168)):_
<details><summary>

<i>Previously, deontologician (Josh Kuhn) wrote…</i></summary>



> We should probably add more extensive tests eventually for the schema.toml format, since it's underspecified right now 
> </details>
> What else should there be?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/679)_

**Comment by dalanmiller** [comment]
Review status: 7 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

_[cli/src/schema.js, line 1 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi-lqA3jEyV9PE1lec:-KNi_ZL3m-XftJEFvB1B:-499146009) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/src/schema.js#L1)):_
<details><summary>

<i>Previously, deontologician (Josh Kuhn) wrote…</i></summary>



> Since this file is two files combined mostly, could you point out which parts are new?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/679)_

**Comment by deontologician** [comment]
Reviewed 1 of 5 files at r5, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[cli/src/schema.js, line 528 [r8]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNicvQ4Vih0qFthoA67:-KNicvQ4Vih0qFthoA68:678074825) ([raw file](https://github.com/rethinkdb/horizon/blob/b9e8c30f390591e665998e800799b5f643060ab9/cli/src/schema.js#L528)):_

> ``` JavaScript
> 
> 
> // Avoiding cylical depdendencies
> ```

typo

---

_[cli/test/schema.spec.js, line 168 [r6]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNi2Ezwwwnys_lm3Rtf:-KNidINKNNgn3DttNB-9:1938460216) ([raw file](https://github.com/rethinkdb/horizon/blob/90bd09b62492a8febfadc132a7298f841742e4be/cli/test/schema.spec.js#L168)):_
<details><summary>

<i>Previously, dalanmiller (Daniel Alan Miller) wrote…</i></summary>



> What else should there be?
> </details>
> Like how to specify indexes etc. I think this is fine for this PR, it would probably be something @tryneus would do since he's the only one who knows the schema format inside and out

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/679)_

**Comment by deontologician** [comment]
:lgtm: there's a typo in the comments. Be sure to squash, there's lots of wip commits

**Comment by dalanmiller** [comment]
Review status: 9 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

_[cli/src/schema.js, line 528 [r8]](https://reviewable.io:443/reviews/rethinkdb/horizon/679#-KNicvQ4Vih0qFthoA67:-KNieWvJWsf4YlxgeYN_:-499146009) ([raw file](https://github.com/rethinkdb/horizon/blob/b9e8c30f390591e665998e800799b5f643060ab9/cli/src/schema.js#L528)):_
<details><summary>

<i>Previously, deontologician (Josh Kuhn) wrote…</i></summary>



> typo
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rethinkdb/horizon/679)_

**Pull request merged**
